// GENERATED BY generate_ciphersuites.go - DO NOT EDIT

package tlshacks

var CipherSuites = map[uint16]struct {
	Name   string
	Grease bool
}{0x0: struct {
	Name   string
	Grease bool
}{Name: "TLS_NULL_WITH_NULL_NULL", Grease: false}, 0x1: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_NULL_MD5", Grease: false}, 0x2: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_NULL_SHA", Grease: false}, 0x3: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_EXPORT_WITH_RC4_40_MD5", Grease: false}, 0x4: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_RC4_128_MD5", Grease: false}, 0x5: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_RC4_128_SHA", Grease: false}, 0x6: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5", Grease: false}, 0x7: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_IDEA_CBC_SHA", Grease: false}, 0x8: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_EXPORT_WITH_DES40_CBC_SHA", Grease: false}, 0x9: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_DES_CBC_SHA", Grease: false}, 0xa: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xb: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA", Grease: false}, 0xc: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_DES_CBC_SHA", Grease: false}, 0xd: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xe: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA", Grease: false}, 0xf: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_DES_CBC_SHA", Grease: false}, 0x10: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0x11: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA", Grease: false}, 0x12: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_DES_CBC_SHA", Grease: false}, 0x13: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0x14: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA", Grease: false}, 0x15: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_DES_CBC_SHA", Grease: false}, 0x16: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0x17: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_EXPORT_WITH_RC4_40_MD5", Grease: false}, 0x18: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_RC4_128_MD5", Grease: false}, 0x19: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA", Grease: false}, 0x1a: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_DES_CBC_SHA", Grease: false}, 0x1b: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0x1e: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_WITH_DES_CBC_SHA", Grease: false}, 0x1f: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0x20: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_WITH_RC4_128_SHA", Grease: false}, 0x21: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_WITH_IDEA_CBC_SHA", Grease: false}, 0x22: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_WITH_DES_CBC_MD5", Grease: false}, 0x23: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_WITH_3DES_EDE_CBC_MD5", Grease: false}, 0x24: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_WITH_RC4_128_MD5", Grease: false}, 0x25: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_WITH_IDEA_CBC_MD5", Grease: false}, 0x26: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA", Grease: false}, 0x27: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA", Grease: false}, 0x28: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_EXPORT_WITH_RC4_40_SHA", Grease: false}, 0x29: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5", Grease: false}, 0x2a: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5", Grease: false}, 0x2b: struct {
	Name   string
	Grease bool
}{Name: "TLS_KRB5_EXPORT_WITH_RC4_40_MD5", Grease: false}, 0x2c: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_NULL_SHA", Grease: false}, 0x2d: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_NULL_SHA", Grease: false}, 0x2e: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_NULL_SHA", Grease: false}, 0x2f: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_AES_128_CBC_SHA", Grease: false}, 0x30: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_AES_128_CBC_SHA", Grease: false}, 0x31: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_AES_128_CBC_SHA", Grease: false}, 0x32: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_AES_128_CBC_SHA", Grease: false}, 0x33: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_AES_128_CBC_SHA", Grease: false}, 0x34: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_AES_128_CBC_SHA", Grease: false}, 0x35: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_AES_256_CBC_SHA", Grease: false}, 0x36: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_AES_256_CBC_SHA", Grease: false}, 0x37: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_AES_256_CBC_SHA", Grease: false}, 0x38: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_AES_256_CBC_SHA", Grease: false}, 0x39: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_AES_256_CBC_SHA", Grease: false}, 0x3a: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_AES_256_CBC_SHA", Grease: false}, 0x3b: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_NULL_SHA256", Grease: false}, 0x3c: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_AES_128_CBC_SHA256", Grease: false}, 0x3d: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_AES_256_CBC_SHA256", Grease: false}, 0x3e: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_AES_128_CBC_SHA256", Grease: false}, 0x3f: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_AES_128_CBC_SHA256", Grease: false}, 0x40: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256", Grease: false}, 0x41: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA", Grease: false}, 0x42: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA", Grease: false}, 0x43: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA", Grease: false}, 0x44: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA", Grease: false}, 0x45: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA", Grease: false}, 0x46: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA", Grease: false}, 0x67: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256", Grease: false}, 0x68: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_AES_256_CBC_SHA256", Grease: false}, 0x69: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_AES_256_CBC_SHA256", Grease: false}, 0x6a: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256", Grease: false}, 0x6b: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256", Grease: false}, 0x6c: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_AES_128_CBC_SHA256", Grease: false}, 0x6d: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_AES_256_CBC_SHA256", Grease: false}, 0x84: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA", Grease: false}, 0x85: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA", Grease: false}, 0x86: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA", Grease: false}, 0x87: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA", Grease: false}, 0x88: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA", Grease: false}, 0x89: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA", Grease: false}, 0x8a: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_RC4_128_SHA", Grease: false}, 0x8b: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0x8c: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_AES_128_CBC_SHA", Grease: false}, 0x8d: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_AES_256_CBC_SHA", Grease: false}, 0x8e: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_RC4_128_SHA", Grease: false}, 0x8f: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0x90: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_AES_128_CBC_SHA", Grease: false}, 0x91: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_AES_256_CBC_SHA", Grease: false}, 0x92: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_RC4_128_SHA", Grease: false}, 0x93: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0x94: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_AES_128_CBC_SHA", Grease: false}, 0x95: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_AES_256_CBC_SHA", Grease: false}, 0x96: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_SEED_CBC_SHA", Grease: false}, 0x97: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_SEED_CBC_SHA", Grease: false}, 0x98: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_SEED_CBC_SHA", Grease: false}, 0x99: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_SEED_CBC_SHA", Grease: false}, 0x9a: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_SEED_CBC_SHA", Grease: false}, 0x9b: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_SEED_CBC_SHA", Grease: false}, 0x9c: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_AES_128_GCM_SHA256", Grease: false}, 0x9d: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_AES_256_GCM_SHA384", Grease: false}, 0x9e: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256", Grease: false}, 0x9f: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384", Grease: false}, 0xa0: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_AES_128_GCM_SHA256", Grease: false}, 0xa1: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_AES_256_GCM_SHA384", Grease: false}, 0xa2: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256", Grease: false}, 0xa3: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384", Grease: false}, 0xa4: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_AES_128_GCM_SHA256", Grease: false}, 0xa5: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_AES_256_GCM_SHA384", Grease: false}, 0xa6: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_AES_128_GCM_SHA256", Grease: false}, 0xa7: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_AES_256_GCM_SHA384", Grease: false}, 0xa8: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_AES_128_GCM_SHA256", Grease: false}, 0xa9: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_AES_256_GCM_SHA384", Grease: false}, 0xaa: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_AES_128_GCM_SHA256", Grease: false}, 0xab: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_AES_256_GCM_SHA384", Grease: false}, 0xac: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_AES_128_GCM_SHA256", Grease: false}, 0xad: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_AES_256_GCM_SHA384", Grease: false}, 0xae: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_AES_128_CBC_SHA256", Grease: false}, 0xaf: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_AES_256_CBC_SHA384", Grease: false}, 0xb0: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_NULL_SHA256", Grease: false}, 0xb1: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_NULL_SHA384", Grease: false}, 0xb2: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_AES_128_CBC_SHA256", Grease: false}, 0xb3: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_AES_256_CBC_SHA384", Grease: false}, 0xb4: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_NULL_SHA256", Grease: false}, 0xb5: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_NULL_SHA384", Grease: false}, 0xb6: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_AES_128_CBC_SHA256", Grease: false}, 0xb7: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_AES_256_CBC_SHA384", Grease: false}, 0xb8: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_NULL_SHA256", Grease: false}, 0xb9: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_NULL_SHA384", Grease: false}, 0xba: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xbb: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xbc: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xbd: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xbe: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xbf: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xc0: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256", Grease: false}, 0xc1: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256", Grease: false}, 0xc2: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256", Grease: false}, 0xc3: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256", Grease: false}, 0xc4: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256", Grease: false}, 0xc5: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256", Grease: false}, 0xc6: struct {
	Name   string
	Grease bool
}{Name: "TLS_SM4_GCM_SM3", Grease: false}, 0xc7: struct {
	Name   string
	Grease bool
}{Name: "TLS_SM4_CCM_SM3", Grease: false}, 0xff: struct {
	Name   string
	Grease bool
}{Name: "TLS_EMPTY_RENEGOTIATION_INFO_SCSV", Grease: false}, 0xa0a: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0x1301: struct {
	Name   string
	Grease bool
}{Name: "TLS_AES_128_GCM_SHA256", Grease: false}, 0x1302: struct {
	Name   string
	Grease bool
}{Name: "TLS_AES_256_GCM_SHA384", Grease: false}, 0x1303: struct {
	Name   string
	Grease bool
}{Name: "TLS_CHACHA20_POLY1305_SHA256", Grease: false}, 0x1304: struct {
	Name   string
	Grease bool
}{Name: "TLS_AES_128_CCM_SHA256", Grease: false}, 0x1305: struct {
	Name   string
	Grease bool
}{Name: "TLS_AES_128_CCM_8_SHA256", Grease: false}, 0x1a1a: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0x2a2a: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0x3a3a: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0x4a4a: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0x5600: struct {
	Name   string
	Grease bool
}{Name: "TLS_FALLBACK_SCSV", Grease: false}, 0x5a5a: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0x6a6a: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0x7a7a: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0x8a8a: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0x9a9a: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0xaaaa: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0xbaba: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0xc001: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_NULL_SHA", Grease: false}, 0xc002: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_RC4_128_SHA", Grease: false}, 0xc003: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xc004: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA", Grease: false}, 0xc005: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA", Grease: false}, 0xc006: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_NULL_SHA", Grease: false}, 0xc007: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA", Grease: false}, 0xc008: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xc009: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA", Grease: false}, 0xc00a: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA", Grease: false}, 0xc00b: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_NULL_SHA", Grease: false}, 0xc00c: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_RC4_128_SHA", Grease: false}, 0xc00d: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xc00e: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA", Grease: false}, 0xc00f: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA", Grease: false}, 0xc010: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_NULL_SHA", Grease: false}, 0xc011: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_RC4_128_SHA", Grease: false}, 0xc012: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xc013: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", Grease: false}, 0xc014: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", Grease: false}, 0xc015: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_anon_WITH_NULL_SHA", Grease: false}, 0xc016: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_anon_WITH_RC4_128_SHA", Grease: false}, 0xc017: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xc018: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_anon_WITH_AES_128_CBC_SHA", Grease: false}, 0xc019: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_anon_WITH_AES_256_CBC_SHA", Grease: false}, 0xc01a: struct {
	Name   string
	Grease bool
}{Name: "TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xc01b: struct {
	Name   string
	Grease bool
}{Name: "TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xc01c: struct {
	Name   string
	Grease bool
}{Name: "TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xc01d: struct {
	Name   string
	Grease bool
}{Name: "TLS_SRP_SHA_WITH_AES_128_CBC_SHA", Grease: false}, 0xc01e: struct {
	Name   string
	Grease bool
}{Name: "TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA", Grease: false}, 0xc01f: struct {
	Name   string
	Grease bool
}{Name: "TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA", Grease: false}, 0xc020: struct {
	Name   string
	Grease bool
}{Name: "TLS_SRP_SHA_WITH_AES_256_CBC_SHA", Grease: false}, 0xc021: struct {
	Name   string
	Grease bool
}{Name: "TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA", Grease: false}, 0xc022: struct {
	Name   string
	Grease bool
}{Name: "TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA", Grease: false}, 0xc023: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256", Grease: false}, 0xc024: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384", Grease: false}, 0xc025: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256", Grease: false}, 0xc026: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384", Grease: false}, 0xc027: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256", Grease: false}, 0xc028: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", Grease: false}, 0xc029: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256", Grease: false}, 0xc02a: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384", Grease: false}, 0xc02b: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", Grease: false}, 0xc02c: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", Grease: false}, 0xc02d: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256", Grease: false}, 0xc02e: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384", Grease: false}, 0xc02f: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", Grease: false}, 0xc030: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", Grease: false}, 0xc031: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256", Grease: false}, 0xc032: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384", Grease: false}, 0xc033: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_RC4_128_SHA", Grease: false}, 0xc034: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA", Grease: false}, 0xc035: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA", Grease: false}, 0xc036: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA", Grease: false}, 0xc037: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256", Grease: false}, 0xc038: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384", Grease: false}, 0xc039: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_NULL_SHA", Grease: false}, 0xc03a: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_NULL_SHA256", Grease: false}, 0xc03b: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_NULL_SHA384", Grease: false}, 0xc03c: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc03d: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc03e: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc03f: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc040: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc041: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc042: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc043: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc044: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc045: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc046: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc047: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc048: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc049: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc04a: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc04b: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc04c: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc04d: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc04e: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc04f: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc050: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc051: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc052: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc053: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc054: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc055: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc056: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc057: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc058: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc059: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc05a: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc05b: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc05c: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc05d: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc05e: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc05f: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc060: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc061: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc062: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc063: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc064: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc065: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc066: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc067: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc068: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc069: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc06a: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc06b: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc06c: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc06d: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc06e: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_ARIA_128_GCM_SHA256", Grease: false}, 0xc06f: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_ARIA_256_GCM_SHA384", Grease: false}, 0xc070: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_ARIA_128_CBC_SHA256", Grease: false}, 0xc071: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_ARIA_256_CBC_SHA384", Grease: false}, 0xc072: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xc073: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384", Grease: false}, 0xc074: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xc075: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_CAMELLIA_256_CBC_SHA384", Grease: false}, 0xc076: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xc077: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384", Grease: false}, 0xc078: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xc079: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_CAMELLIA_256_CBC_SHA384", Grease: false}, 0xc07a: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc07b: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc07c: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc07d: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc07e: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc07f: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_RSA_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc080: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc081: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_DSS_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc082: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc083: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_DSS_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc084: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc085: struct {
	Name   string
	Grease bool
}{Name: "TLS_DH_anon_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc086: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc087: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc088: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc089: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_ECDSA_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc08a: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc08b: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc08c: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc08d: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDH_RSA_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc08e: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc08f: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc090: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc091: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc092: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_CAMELLIA_128_GCM_SHA256", Grease: false}, 0xc093: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_CAMELLIA_256_GCM_SHA384", Grease: false}, 0xc094: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xc095: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_CAMELLIA_256_CBC_SHA384", Grease: false}, 0xc096: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xc097: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_CAMELLIA_256_CBC_SHA384", Grease: false}, 0xc098: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xc099: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_CAMELLIA_256_CBC_SHA384", Grease: false}, 0xc09a: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_CAMELLIA_128_CBC_SHA256", Grease: false}, 0xc09b: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_CAMELLIA_256_CBC_SHA384", Grease: false}, 0xc09c: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_AES_128_CCM", Grease: false}, 0xc09d: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_AES_256_CCM", Grease: false}, 0xc09e: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_AES_128_CCM", Grease: false}, 0xc09f: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_AES_256_CCM", Grease: false}, 0xc0a0: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_AES_128_CCM_8", Grease: false}, 0xc0a1: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_WITH_AES_256_CCM_8", Grease: false}, 0xc0a2: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_AES_128_CCM_8", Grease: false}, 0xc0a3: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_AES_256_CCM_8", Grease: false}, 0xc0a4: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_AES_128_CCM", Grease: false}, 0xc0a5: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_AES_256_CCM", Grease: false}, 0xc0a6: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_AES_128_CCM", Grease: false}, 0xc0a7: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_AES_256_CCM", Grease: false}, 0xc0a8: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_AES_128_CCM_8", Grease: false}, 0xc0a9: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_AES_256_CCM_8", Grease: false}, 0xc0aa: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_DHE_WITH_AES_128_CCM_8", Grease: false}, 0xc0ab: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_DHE_WITH_AES_256_CCM_8", Grease: false}, 0xc0ac: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_AES_128_CCM", Grease: false}, 0xc0ad: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_AES_256_CCM", Grease: false}, 0xc0ae: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8", Grease: false}, 0xc0af: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8", Grease: false}, 0xc0b0: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECCPWD_WITH_AES_128_GCM_SHA256", Grease: false}, 0xc0b1: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECCPWD_WITH_AES_256_GCM_SHA384", Grease: false}, 0xc0b2: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECCPWD_WITH_AES_128_CCM_SHA256", Grease: false}, 0xc0b3: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECCPWD_WITH_AES_256_CCM_SHA384", Grease: false}, 0xc0b4: struct {
	Name   string
	Grease bool
}{Name: "TLS_SHA256_SHA256", Grease: false}, 0xc0b5: struct {
	Name   string
	Grease bool
}{Name: "TLS_SHA384_SHA384", Grease: false}, 0xc100: struct {
	Name   string
	Grease bool
}{Name: "TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC", Grease: false}, 0xc101: struct {
	Name   string
	Grease bool
}{Name: "TLS_GOSTR341112_256_WITH_MAGMA_CTR_OMAC", Grease: false}, 0xc102: struct {
	Name   string
	Grease bool
}{Name: "TLS_GOSTR341112_256_WITH_28147_CNT_IMIT", Grease: false}, 0xc103: struct {
	Name   string
	Grease bool
}{Name: "TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_L", Grease: false}, 0xc104: struct {
	Name   string
	Grease bool
}{Name: "TLS_GOSTR341112_256_WITH_MAGMA_MGM_L", Grease: false}, 0xc105: struct {
	Name   string
	Grease bool
}{Name: "TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_S", Grease: false}, 0xc106: struct {
	Name   string
	Grease bool
}{Name: "TLS_GOSTR341112_256_WITH_MAGMA_MGM_S", Grease: false}, 0xcaca: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0xcca8: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256", Grease: false}, 0xcca9: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256", Grease: false}, 0xccaa: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256", Grease: false}, 0xccab: struct {
	Name   string
	Grease bool
}{Name: "TLS_PSK_WITH_CHACHA20_POLY1305_SHA256", Grease: false}, 0xccac: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256", Grease: false}, 0xccad: struct {
	Name   string
	Grease bool
}{Name: "TLS_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256", Grease: false}, 0xccae: struct {
	Name   string
	Grease bool
}{Name: "TLS_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256", Grease: false}, 0xd001: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256", Grease: false}, 0xd002: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_AES_256_GCM_SHA384", Grease: false}, 0xd003: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_AES_128_CCM_8_SHA256", Grease: false}, 0xd005: struct {
	Name   string
	Grease bool
}{Name: "TLS_ECDHE_PSK_WITH_AES_128_CCM_SHA256", Grease: false}, 0xdada: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0xeaea: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}, 0xfafa: struct {
	Name   string
	Grease bool
}{Name: "", Grease: true}}
