//go:build generate

//go:generate go1.18 run generate_extensions.go

package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

const sourceURL = `https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values-1.csv`

const outputFilename = "extensions.go"

const outputFormat = `// GENERATED BY generate_extensions.go - DO NOT EDIT

package tlshacks

var Extensions = %#v
`

func main() {
	client := &http.Client{Timeout: 1 * time.Minute}
	resp, err := client.Get(sourceURL)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		log.Fatalf("%s: %d %s", sourceURL, resp.StatusCode, resp.Status)
	}

	reader := csv.NewReader(resp.Body)

	// Discard header
	if _, err := reader.Read(); err != nil {
		log.Fatal(err)
	}

	extensions := make(map[uint16]string)

	for {
		row, err := reader.Read()
		if err == io.EOF {
			break
		} else if err != nil {
			log.Fatal(err)
		}

		var (
			valueString = row[0]
			name        = row[1]
		)
		if strings.Contains(name, "Reserved") || strings.Contains(name, "Unassigned") {
			continue
		}
		if index := strings.Index(name, " (renamed from"); index != -1 {
			name = name[:index]
		}
		value, err := strconv.ParseUint(valueString, 0, 16)
		if err != nil {
			log.Fatal(err)
		}
		extensions[uint16(value)] = name
	}

	if err := os.WriteFile(outputFilename, []byte(fmt.Sprintf(outputFormat, extensions)), 0666); err != nil {
		log.Fatal(err)
	}
}
